name: Benchmark

on: [push, pull_request]

jobs:
  tests-linux:
    runs-on: ubuntu-latest # TODO: change this to tremor-bench-dev

    env:
      TREMOR_PATH: "${{ github.workspace }}/tremor-script/lib"

    steps:

      - name: clone repository
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: install deps
        run: sudo apt-get -qy update && sudo apt-get install -y libssl-dev libssl1.1

      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p tremor-cli 

      - name: run benchmarks
        run: |
          ./target/release/tremor test bench tremor-cli/tests/bench/ -o

      - name: download previous artifact
        uses: actions/download-artifact@v2
        with:
          name: data.json

      - name: download previous artifact
        uses: actions/download-artifact@v2
        with:
          name: recent.json

      - name: parse benchmark results
        env:
          TREMOR_BENCH_VERSION: 0.1.2
        run: |
          curl -o tremor-bench.zip -L https://github.com/humancalico/tremor-benchmark/releases/download/v$TREMOR_BENCH_VERSION/tremor-benchmark-x86_64-unknown-linux-musl.zip
          unzip tremor-bench.zip
          touch data.json
          touch recent.json
          ./tremor-benchmark data.json recent.json report.json $GITHUB_SHA
        
      - name: upload benchmark results as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: data.json

      - name: upload benchmark results as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: recent.json

