name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.profile }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # test-kind: [integration, api, unit, command]
        include:
          - os: macos-11.0
            kind: test
            profile: debug
          - os: ubuntu-20.04
            kind: lint
            profile: debug
          - os: ubuntu-20.04
            kind: test
            profile: debug

      # Always run main branch builds to completion. This allows the cache to
      # stay mostly up-to-date in situations where a single job fails due to
      # e.g. a flaky test.
      # Don't fast-fail on tag build because publishing binaries shouldn't be
      # prevented if if any of the stages fails (which can be a false negative).
      fail-fast: ${{ github.event_name == 'pull_request' || (github.ref !=
        'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')) }}

    env:
      RUST_BACKTRACE: full
      CARGO_TERM_COLOR: always
      RUSTFLAGS: -D warnings
      PROPTEST_CASES: 2500
      TREMOR_PATH: ${{ github.workspace }}/tremor-script/lib


    steps:
      - name: clone repository
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy

      - name: log versions
        run: |
          rustc --version
          cargo --version

      - name: check rustfmt
        if: matrix.kind == 'lint'
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: check clippy
        if: matrix.kind == 'lint'
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: build release
        if: (matrix.kind == 'test' || matrix.kind == 'bench') && matrix.profile == 'release'
        run: cargo build --all --release --locked -vv

      - name: build debug
        if: (matrix.kind == 'test' || matrix.kind == 'bench') && matrix.profile == 'debug'
        run: cargo build --all --locked

      - name: test release
        if: matrix.kind == 'test' && matrix.profile == 'release'
        run: cargo test --all --release --locked

      - name: test debug
        if: matrix.kind == 'test' && matrix.profile == 'debug'
        run: |
          cargo test --all --locked --doc
          cargo test --all --locked

      # - name: test ${{ matrix.test-kind }} debug
      #   if: matrix.kind == 'test' && matrix.profile == 'debug'
      #   run: |
      #     cargo build -p tremor-cli --locked -- test ${{ matrix.test-kind }} tremor-cli/tests

      # - name: test ${{ matrix.test-kind }} release
      #   if: matrix.kind == 'test' && matrix.profile == 'release'
      #   run: |
      #     cargo build --release -p tremor-cli --locked -- test ${{ matrix.test-kind }} tremor-cli/tests

      # - name: upload error logs
      #   uses: actions/upload-artifact@v2
      #   if: failure()
      #   with:
      #     name: test-errors
      #     path: tremor-cli/tests/**/*.log

      # - name: run cargo-tarpaulin
      #   uses: actions-rs/tarpaulin@v0.1
      #   with:
      #     version: "0.16.0"
      #     args: --exclude-files target* tremor-cli tremor-api deprecated **/errors.rs --out Lcov --all

      # - name: coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: ./lcov.info

      # TODO add a github release workflow
